version: "3.9"
services:
  user-service:
    build:
      context: .
      dockerfile: ./applications/user-service/build/Dockerfile
    ports:
      - "8080:3000"
  temperature-service:
    build:
      context: .
      dockerfile: ./applications/temperature-service/build/Dockerfile
    ports:
      - "8081:3000"